# temporarily disable trigger during pipeline development
trigger: none 
pr: none
    
resources:
- repo: self


pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sleep 30 
- stage: Deploy
  displayName: Deploy
  jobs:  
  - job: Deploy
    displayName: Deploy
    steps:
    - steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sleep 30 
