# temporarily disable trigger during pipeline development
trigger:
- qa
- uat
pr: none
    
steps:

- template: azure-pipelines-qa.yml

- template: azure-pipelines-uat.yml
 
- template: azure-pipelines-preprod.yml
